/*
const schools = [
    "Australian National University",
    "University of Canberra",
    "Australian Catholic University",
    "Charles Sturt University",
    "Macquarie University",
    "The University of Newcastle",
    "The University of New South Wales",
    "The University of Sydney",
    "University of New England",
    "University of Technology Sydney",
    "University of Wollongong",
    "Western Sydney University",
    "Charles Darwin University",
    "Bond University",
    "Central Queensland University",
    "Griffith University",
    "James Cook University",
    "Queensland University of Technology",
    "Southern Cross University",
    "The University of Queensland",
    "University of Southern Queensland",
    "University of Sunshine Coast",
    "Carnegie Mellon University",
    "Flinders University",
    "The University of Adelaide",
    "Torrens University Australia",
    "University College London",
    "University of South Australia",
    "University of Tasmania",
    "Deakin University",
    "La Trobe University",
    "Monash University",
    "RMIT University",
    "Swinburne University of Technology",
    "University of Divinity",
    "University of Melbourne",
    "Federation University",
    "Victoria University",
    "Curtin University of Technology",
    "Edith Cowan University",
    "Murdoch University",
    "The University of Western Australia",
    "The University of Notre Dame Australia",
];
*/

const schools = ['01. Kevin (ACU)',
    '02. Nguyen Minh Sang (ACU)',
    '03. Mai (CSU)',
    '04. My (CSU)',
    '05. Bach (MQU)',
    '06. Chris (MQU)',
    '07. Hải (MQU)',
    '08. Hằng (MQU)',
    '09. Lee (MQU)',
    '10. Moni Vuong (MQU)',
    '11. Nguyễn Thành Long (MQU)',
    '12. Phuong (MQU)',
    '13. Quân (MQU)',
    '14. Sam (MQU)',
    '15. Việt Phạm (MQU)',
    '16. Winnie (MQU)',
    '17. Duong (NIDA)',
    '18. My Holland (SCU)',
    '19. Minh (TAFE NSW)',
    '20. Nic (TAFE NSW)',
    '21. Andy Mai (UNSW)',
    '22. Duc (UNSW)',
    '23. Duy (UNSW)',
    '24. Hien Truong (UNSW)',
    '25. Dr Hiệp (UNSW)',
    '26. Nhut (UNSW)',
    '27. Thang (UNSW)',
    '28. Thi Tran (UNSW)',
    '29. Thu (UNSW)',
    '30. Truc Tran (UNSW)',
    '31. Tuyet Vu (UNSW)',
    '32. Vivian (UNSW)',
    '33. Ben (UON)',
    '34. Ha (UON)',
    '35. Phoebe Pham (UON)',
    '36. Hieu /Hill/ (USYD)',
    '37. Minh Beta (USYD)',
    '38. Nguyen (USYD)',
    '39. Tong (USYD)',
    '40. Andy (UTS)',
    '41. Bao (UTS)',
    '42. Cat Thao Nguyen (UTS)',
    '43. Chanh (UTS)',
    '44. Chris (UTS)',
    '45. Hai Ho (UTS)',
    '46. Hải Võ (UTS)',
    '47. Huong (UTS)',
    '48. Khoa (UTS)',
    '49. Linh (UTS)',
    '50. Long (UTS)',
    '51. Sherly (UTS)',
    '52. TAI (UTS)',
    '53. Trà My (UTS)',
    '54. Trung (UTS)',
    '55. Van (UTS)',
    '56. Vannessa (UTS)',
    '57. Vũ Đức Toàn (UTS)',
    '58. Steven (UOW)',
    '59. An (WSU)',
    '60. Binh (WSU)',
    '61. Hoang (WSU)',
    '62. Khanh (WSU)',
    '63. Kiệt (WSU)',
    '64. Long (WSU)',
    '65. Nguyen (WSU)',
    '66. Phuong (WSU)',
    '67. Sophie (WSU)',
    '68. Trang (WSU)'];