const schools = [
    "Australian National University",
    "University of Canberra",
    "Australian Catholic University",
    "Charles Sturt University",
    "Macquarie University",
    "The University of Newcastle",
    "The University of New South Wales",
    "The University of Sydney",
    "University of New England",
    "University of Technology Sydney",
    "University of Wollongong",
    "Western Sydney University",
    "Charles Darwin University",
    "Bond University",
    "Central Queensland University",
    "Griffith University",
    "James Cook University",
    "Queensland University of Technology",
    "Southern Cross University",
    "The University of Queensland",
    "University of Southern Queensland",
    "University of Sunshine Coast",
    "Carnegie Mellon University",
    "Flinders University",
    "The University of Adelaide",
    "Torrens University Australia",
    "University College London",
    "University of South Australia",
    "University of Tasmania",
    "Deakin University",
    "La Trobe University",
    "Monash University",
    "RMIT University",
    "Swinburne University of Technology",
    "University of Divinity",
    "University of Melbourne",
    "Federation University",
    "Victoria University",
    "Curtin University of Technology",
    "Edith Cowan University",
    "Murdoch University",
    "The University of Western Australia",
    "The University of Notre Dame Australia",
];